Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -67,3 +67,35 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+
+  deploy:
+    needs:
+      - package-and-publish  # Ensure CD only runs after CI and packaging are done
+    runs-on: self-hosted  # This will use your self-hosted runner
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+          registry: ghcr.io
+
+      - name: Pull Docker Image
+        run: |
+          # Pull the latest image from GitHub Container Registry
+          sudo docker pull ghcr.io/dzangar/cloud-gh-actions-workshop:latest
+  
+      - name: Deploy Docker Container
+        run: |
+          # Gracefully stop and remove the old container if exists
+          sudo docker stop my-container1 || true
+          sudo docker rm my-container1 || true
+          
+          # Run the new container
+          sudo docker run -d --name my-container1 -p 81:8080 ghcr.io/dzangar/cloud-gh-actions-workshop:latest
+  
+          # Clean up unused Docker resources
+          sudo docker system prune -f
